# Generated by Django 4.1.5 on 2024-07-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_profit_amount_alter_saledetail_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='selling_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
