# Generated by Django 4.1.5 on 2024-07-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='customer1', max_length=256),
        ),
    ]
